version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html:ro
      - ./frontend/dock.png:/usr/share/nginx/html/dock.png:ro

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - BACKEND_CORS_ORIGINS=http://localhost
      - LOG_LEVEL=INFO
