version: '3.8'

services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "80:80"
  #   environment:
  #     - VITE_PUBLIC_API_BASE=http://localhost:8000
  #   depends_on:
  #     - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - BACKEND_CORS_ORIGINS=http://localhost
      - LOG_LEVEL=INFO
